$(document).ready(function(){
	$('.hamburger').click(function(){
		$(this).toggleClass('open');
		$('.drop-down-menu').toggleClass('open');
	});
	$('.drop-down-menu').click(function(){
		$(this).removeClass('open');
		$('.hamburger').removeClass('open');
	});
});